name: wflow

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - numpy>=1.12
  - scipy>=1.0
  - gdal>=2.2.4
  - netcdf4>=1.4.1
  - cftime>=1.0.1
  - pyproj>=1.9
  - thrift>=0.11
  - pyinstaller>=3.3
  - versioneer>=0.18
  - pywin32>=221
  - setuptools>=38
  - pip>=9.0.3
  - dateutil>=2.7
  - pip:
    - bmi-python
